@startuml
!theme materia
'Define the skinparam for the font size
skinparam defaultFontSize 24

'Define the components
cloud {
    [OpenAI] as openai
}
node {
    [Let Us Webtoon] as webtoon
}
database {
    [Firebase] as firebase
}

'Define the relationships
openai <-- webtoon : prompt
openai --> webtoon : story
openai --> webtoon : image
firebase <-- webtoon : credentials
firebase --> webtoon : verification
firebase <--> webtoon : webtoon
@enduml