@startuml
!theme materia
title Create an account
skinparam defaultFontSize 24

start
:User provides authentication information;
:User initiates registration;
:System confirms registration request;
:User confirms registration response;
:System finalizes registration;
:System navigates user to content library;
stop
@enduml