@startuml
!theme materia
title Create a new webtoon
skinparam defaultFontSize 24

start
:User enters text prompt;
:User clicks create button;
:System sends text prompt to AI-generated text API;
:System receives webtoon story, scenes, and script;
:System sends story and scenes to AI image creation API;
:System receives webtoon images;
:System places speech bubbles over images with script;
:System creates webtoon;
:System assigns unique ID to webtoon;
:System stores webtoon in user's webtoon list;
stop
@enduml