@startuml
!theme materia
title Create a new webtoon
skinparam defaultFontSize 24

start
:User provides creative input;
:User requests content generation;
:System processes creative input through AI;
:System compiles narrative and visual elements;
:System integrates narrative with visuals;
:System finalizes webtoon creation;
:System catalogues webtoon with an identifier;
:System archives webtoon in user's collection;
stop
@enduml