@startuml
!theme materia
title Delete a webtoon
skinparam defaultFontSize 24

start
:User chooses webtoon for removal;
:User initiates removal process;
:System requests removal confirmation;
if (User agrees to proceed?) then (yes)
  :System completes removal of webtoon;
else (no)
  :System discontinues removal process;
endif
stop
@enduml