@startuml
!theme materia
'Define the skinparam for the font size
skinparam defaultFontSize 24

package "Webtoon App" {
  [UI Layer] as UI
  [Business Logic] as BL
  [Data Access] as DA
}

database "Firebase" {
  [Database]
}

cloud "OpenAI" {
  [AI API] 
}

UI ..> BL : use >
BL ..> DA : use >
DA ..> [Database] : read/write >
BL ..> [AI API] : requests >
@enduml
