@startuml
!theme materia
title Log into account
skinparam defaultFontSize 24

start
:User provides login information;
:User requests access;
:System checks login information;
if (Is the information correct?) then (yes)
  :System allows entry to user profile;
  :System navigates user to content library;
else (no)
  :System informs of unsuccessful attempt;
endif
stop
@enduml