@startuml
!theme materia
title Manage user account
skinparam defaultFontSize 24

start
:Administrator clicks manage users button;
:System displays user list page;
:Administrator views, edits, deletes, or suspends user account;
:Administrator clicks save button;
:System updates user account;
stop
@enduml