@startuml
!theme materia
title Monitor comments
skinparam defaultFontSize 24

start
:Administrator accesses comment list;
:Administrator filters comments by user and message;
:Administrator deletes comment;
stop
@enduml
