@startuml
!theme materia
title Report a user
skinparam defaultFontSize 24

start
:User selects another user;
:User clicks report button;
:System prompts user to enter reason;
:User enters reason;
:System saves report to admin list;
:System informs user of outcome;
stop
@enduml
