@startuml
!theme materia
title View a webtoon
skinparam defaultFontSize 24

start
:User chooses webtoon to view;
:System presents selected webtoon;
:User navigates through webtoon content;
stop
@enduml