// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCsckU8xLl4sRSQHtFaBGpbNqkMCYCRqM',
    appId: '1:994319988415:web:255e8b6068bf4a5ba9f80a',
    messagingSenderId: '994319988415',
    projectId: 'let-us-webtoon',
    authDomain: 'let-us-webtoon.firebaseapp.com',
    storageBucket: 'let-us-webtoon.appspot.com',
    measurementId: 'G-6266GN7VYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ13YrzcmTiTgJsJmb-VVMCrhIKz42OyQ',
    appId: '1:994319988415:android:dd537a3ef21bc39ba9f80a',
    messagingSenderId: '994319988415',
    projectId: 'let-us-webtoon',
    storageBucket: 'let-us-webtoon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIS_dp7n41drUNhMhFcn1gH7F6Qx4U4ho',
    appId: '1:994319988415:ios:50ef05078e47ce4ba9f80a',
    messagingSenderId: '994319988415',
    projectId: 'let-us-webtoon',
    storageBucket: 'let-us-webtoon.appspot.com',
    iosBundleId: 'com.example.letUsWebtoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIS_dp7n41drUNhMhFcn1gH7F6Qx4U4ho',
    appId: '1:994319988415:ios:571a369b422b7e9ba9f80a',
    messagingSenderId: '994319988415',
    projectId: 'let-us-webtoon',
    storageBucket: 'let-us-webtoon.appspot.com',
    iosBundleId: 'com.example.letUsWebtoon.RunnerTests',
  );
}
